# Generated by Django 3.0.7 on 2020-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0002_auto_20200627_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2020-06-27'),
        ),
    ]
